/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentCanceledRouteImport } from './routes/payment.canceled'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as ApiSuggestCuisineRouteImport } from './routes/api/suggest-cuisine'
import { Route as ApiChefAiRouteImport } from './routes/api/chef-ai'
import { Route as ApiMapsGeocodeRouteImport } from './routes/api/maps.geocode'
import { Route as ApiMapsConfigRouteImport } from './routes/api/maps.config'
import { Route as ApiMapsAutocompleteRouteImport } from './routes/api/maps.autocomplete'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCanceledRoute = PaymentCanceledRouteImport.update({
  id: '/payment/canceled',
  path: '/payment/canceled',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestCuisineRoute = ApiSuggestCuisineRouteImport.update({
  id: '/api/suggest-cuisine',
  path: '/api/suggest-cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChefAiRoute = ApiChefAiRouteImport.update({
  id: '/api/chef-ai',
  path: '/api/chef-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapsGeocodeRoute = ApiMapsGeocodeRouteImport.update({
  id: '/api/maps/geocode',
  path: '/api/maps/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapsConfigRoute = ApiMapsConfigRouteImport.update({
  id: '/api/maps/config',
  path: '/api/maps/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapsAutocompleteRoute = ApiMapsAutocompleteRouteImport.update({
  id: '/api/maps/autocomplete',
  path: '/api/maps/autocomplete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/refund': typeof RefundRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/chef-ai': typeof ApiChefAiRoute
  '/api/suggest-cuisine': typeof ApiSuggestCuisineRoute
  '/invite/$code': typeof InviteCodeRoute
  '/payment/canceled': typeof PaymentCanceledRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/maps/autocomplete': typeof ApiMapsAutocompleteRoute
  '/api/maps/config': typeof ApiMapsConfigRoute
  '/api/maps/geocode': typeof ApiMapsGeocodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/refund': typeof RefundRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/chef-ai': typeof ApiChefAiRoute
  '/api/suggest-cuisine': typeof ApiSuggestCuisineRoute
  '/invite/$code': typeof InviteCodeRoute
  '/payment/canceled': typeof PaymentCanceledRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/maps/autocomplete': typeof ApiMapsAutocompleteRoute
  '/api/maps/config': typeof ApiMapsConfigRoute
  '/api/maps/geocode': typeof ApiMapsGeocodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/refund': typeof RefundRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/chef-ai': typeof ApiChefAiRoute
  '/api/suggest-cuisine': typeof ApiSuggestCuisineRoute
  '/invite/$code': typeof InviteCodeRoute
  '/payment/canceled': typeof PaymentCanceledRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/maps/autocomplete': typeof ApiMapsAutocompleteRoute
  '/api/maps/config': typeof ApiMapsConfigRoute
  '/api/maps/geocode': typeof ApiMapsGeocodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/pro'
    | '/refund'
    | '/settings'
    | '/terms'
    | '/api/chef-ai'
    | '/api/suggest-cuisine'
    | '/invite/$code'
    | '/payment/canceled'
    | '/payment/success'
    | '/api/maps/autocomplete'
    | '/api/maps/config'
    | '/api/maps/geocode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/pro'
    | '/refund'
    | '/settings'
    | '/terms'
    | '/api/chef-ai'
    | '/api/suggest-cuisine'
    | '/invite/$code'
    | '/payment/canceled'
    | '/payment/success'
    | '/api/maps/autocomplete'
    | '/api/maps/config'
    | '/api/maps/geocode'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/pro'
    | '/refund'
    | '/settings'
    | '/terms'
    | '/api/chef-ai'
    | '/api/suggest-cuisine'
    | '/invite/$code'
    | '/payment/canceled'
    | '/payment/success'
    | '/api/maps/autocomplete'
    | '/api/maps/config'
    | '/api/maps/geocode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProRoute: typeof ProRoute
  RefundRoute: typeof RefundRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiChefAiRoute: typeof ApiChefAiRoute
  ApiSuggestCuisineRoute: typeof ApiSuggestCuisineRoute
  InviteCodeRoute: typeof InviteCodeRoute
  PaymentCanceledRoute: typeof PaymentCanceledRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiMapsAutocompleteRoute: typeof ApiMapsAutocompleteRoute
  ApiMapsConfigRoute: typeof ApiMapsConfigRoute
  ApiMapsGeocodeRoute: typeof ApiMapsGeocodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/canceled': {
      id: '/payment/canceled'
      path: '/payment/canceled'
      fullPath: '/payment/canceled'
      preLoaderRoute: typeof PaymentCanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-cuisine': {
      id: '/api/suggest-cuisine'
      path: '/api/suggest-cuisine'
      fullPath: '/api/suggest-cuisine'
      preLoaderRoute: typeof ApiSuggestCuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chef-ai': {
      id: '/api/chef-ai'
      path: '/api/chef-ai'
      fullPath: '/api/chef-ai'
      preLoaderRoute: typeof ApiChefAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maps/geocode': {
      id: '/api/maps/geocode'
      path: '/api/maps/geocode'
      fullPath: '/api/maps/geocode'
      preLoaderRoute: typeof ApiMapsGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maps/config': {
      id: '/api/maps/config'
      path: '/api/maps/config'
      fullPath: '/api/maps/config'
      preLoaderRoute: typeof ApiMapsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maps/autocomplete': {
      id: '/api/maps/autocomplete'
      path: '/api/maps/autocomplete'
      fullPath: '/api/maps/autocomplete'
      preLoaderRoute: typeof ApiMapsAutocompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProRoute: ProRoute,
  RefundRoute: RefundRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiChefAiRoute: ApiChefAiRoute,
  ApiSuggestCuisineRoute: ApiSuggestCuisineRoute,
  InviteCodeRoute: InviteCodeRoute,
  PaymentCanceledRoute: PaymentCanceledRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiMapsAutocompleteRoute: ApiMapsAutocompleteRoute,
  ApiMapsConfigRoute: ApiMapsConfigRoute,
  ApiMapsGeocodeRoute: ApiMapsGeocodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
